[theme]
# Core dark mode colors
primaryColor = "#4CAF50"              # Accent color (buttons, sliders, links) - green for visibility
backgroundColor = "#000000"           # Main page background (black)
secondaryBackgroundColor = "#696969"  # for sidebar & widget backgrounds
textColor = "#FFFFFF"                 # All main text in white
font = "sans serif"                   # Clean, modern font
